### ISSUE TITLE
weight_manager cannot be MIXed when push_mixer is used

### ISSUE THREAD

**Issue by kmaehashi** [jubatus/jubatus_core#65]
When using push_mixer MIX strategy, weight_manager is not MIXed between servers.
As a result, IDF values may become more inaccurate than when using linear_mixer.

**Comment by kumagi** [comment]
If we choose to use `vector_clock`. sequences are below.
1. compare the clock
2. if clock is different, newer clock owner must send **whole count data of the clock** to older clock owner. whole data may be very big so that it can reach multiple Giga-Bytes.
3. whole count data will occupy the network resource. it may be harmful.
4. above procedure will occur for whole cluster for only **one update** method.

we should select more cost-effective procedure like delivery-tree or other.
how about skip-graph?
